server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/cards/**
        - id: loans-service
          uri: lb://loans-service
          predicates:
            - Path=/loans/**
#    gateway:
#      routes:
#        - id: account-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/accounts/**
#        - id: loans-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/loans/**
#        - id: card-service
#          uri: http://localhost:8083
#          predicates:
#            - Path=/cards/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-secondes: 1
    register-with-eureka: true
    fetch-repository: true